admin/config/routes.rb
Workarea::Admin::Engine.routes.draw do
  mount Sidekiq::Web,
    at: '/sidekiq',
    constraints: Workarea::RoutesConstraints::SuperAdmin.new,
    anchor: false

  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resource :activity, only: :show
    resources :trash, only: :index do
      member { post :restore }
    end
    resources :timeline, only: :show
    resources :featured_products, only: [:edit, :update] do
      member do
        get :select
        post :add
        delete :remove
      end
    end

    resources :bulk_actions, only: [:create, :destroy] do
      member do
        get :selected
      end
    end
    resources :bulk_action_deletions, only: :edit do
      member { delete :confirm }
    end
    resources :bulk_action_product_edits, only: [:edit, :update] do
      member do
        get :review
        post :publish
      end
    end
    resources :bulk_action_sequential_product_edits, only: :edit do
      member do
        post :publish

        get 'product/:index', action: 'product', as: :product
        patch 'product/:index', action: 'update_product'
      end
    end
    resources :bulk_action_order_exports,
      only: [:show, :edit, :update], controller: :bulk_action_exports
    resources :bulk_action_user_exports,
      only: [:show, :edit, :update], controller: :bulk_action_exports
    resources :bulk_action_pricing_discount_code_list_exports,
      only: [:show, :edit, :update], controller: :bulk_action_exports
    resources :bulk_action_email_signup_exports,
      only: [:show, :edit, :update], controller: :bulk_action_exports

    resources :commentables, only: [] do
      resources :comments, except: :new do
        collection do
          put :subscribe
          put :unsubscribe
        end
      end
    end

    resources :content_assets do
      collection do
        get 'insert', to: 'content_assets#insert'
      end
    end

    resources :data_files, only: :index do
      member { get :errors }
    end
    resources :data_file_exports, only: [:show, :new, :create]
    resources :data_file_imports, only: [:new, :create] do
      get :sample, on: :collection
    end
    resources :data_file_tax_imports, only: [:new, :create]

    resource :impersonations, only: [:create, :destroy]
    resource :guest_browsing, only: [:create, :destroy]

    resources :help
    resources :help_assets, only: [:index, :create, :destroy]

    # TODO: v4 use help_articles/ over help/
    get 'help_articles/:id', to: redirect('help/%{id}'), as: :help_article

    resources :content do
      member do
        get :advanced
        get :preview
      end

      resources :areas, only: [] do
        resources :blocks, except: [:show, :new, :edit], controller: 'content_blocks' do
          collection do
            patch :move
          end

          member do
            post :copy
          end
        end
      end
    end

    resources :content_block_drafts, only: :create

    resources :create_releases, only: [:index, :create, :edit, :update] do
      member do
        get :plan
      end
    end

    resources :releases do
      resources :changesets, only: [:index, :destroy]
      resources :releasables, only: [:index, :show]

      resources :undos, controller: 'create_release_undos', only: [:new, :create] do
        member { get :review }
      end

      member do
        get 'edit_for/:type', action: :edit_for, as: :edit_for
        patch :publish
      end

      collection do
        get 'list'
        get 'calendar_feed/:token/site_planner.ics', action: :calendar_feed, as: :calendar_feed
      end
    end

    resource :release_session, only: :create do
      post :touch
    end

    resource :report do
      get :average_order_value
      get :customers
      get :first_time_vs_returning_sales
      get :insights
      get :low_inventory
      get :reference
      get :sales_by_category
      get :sales_by_country
      get :sales_by_discount
      get :sales_by_product
      get :sales_by_sku
      get :sales_by_tender
      get :sales_by_traffic_referrer
      get :sales_over_time
      get :searches
      get :timeline

      resources :custom_events, only: [:create, :update, :destroy]

      post :export
      get '/:id/download', action: :download, as: :download
    end

    get 'jump_to', to: 'jump_to#index'

    resources :orders, only: [:index, :show] do
      member do
        get :attributes
        get :timeline
        get :fraud
      end

      resources :shippings, only: :index
    end

    # TODO remove in v4
    resources :shippings, only: :show

    resources :payments, only: :show

    resources :payment_transactions, only: [:index, :show]

    resources :fulfillments, only: :show
    resources :fulfillment_skus do
      resources :fulfillment_tokens, as: :tokens
    end

    resources :catalog_products, except: [:new, :create] do
      resources :variants, controller: 'catalog_variants', except: :show do
        collection do
          post :move
        end
      end
      resource :recommendations, only: [:edit, :update]
      resources :categorizations, only: [:index, :create, :destroy]

      resources :images, only: [:index, :create, :edit, :update, :destroy], controller: 'catalog_product_images' do
        collection do
          post :positions
          get  :options
        end
      end

      member do
        get :content
        get :insights
      end

      collection do
        get :filters
        get :details
      end
    end

    resources :catalog_product_copies, only: [:new, :create]

    resources :create_catalog_products, except: :show do
      member do
        get :variants
        post :save_variants

        get :details
        post :save_details

        get :images
        post :save_images

        get :content
        post :save_content

        get :categorization
        post :save_categorization

        get :publish
        post :save_publish
      end
    end

    resources :create_users, except: :show

    get '/catalog_variants/details', to: 'catalog_variants#details'

    resources :catalog_categories, except: [:new, :create] do
      member do
        get :insights
      end
    end

    resources :product_list, only: [] do
      resources :product_rules, except: [:show] do
        member do
          get :preview
        end
      end
    end

    resources :create_catalog_categories, except: :show do
      member do
        get :products
        get :featured_products
        get :rules
        get :new_rule
        get 'edit_rule/:rule_id', action: :edit_rule, as: :edit_rule
        get :content
        get :taxonomy
        post :save_taxonomy
        get :navigation
        post :save_navigation
        get :publish
        post :save_publish
      end
    end

    resources :create_pricing_discounts, except: :show do
      collection do
        get :details
        get :rules
      end
      member do
        get :publish
        post :save_publish
      end
    end

    resources :pricing_discount_code_lists do
      member { get :promo_codes }
    end

    resources :pricing_overrides, only: [:edit, :update]

    resources :content_pages, except: [:new, :create]

    resources :content_page_copies, only: [:new, :create]

    resources :create_content_pages, except: :show do
      member do
        get :content
        get :taxonomy
        post :save_taxonomy
        get :navigation
        post :save_navigation
        get :publish
        post :save_publish
      end
    end

    resources :content_presets, only: [:new, :create, :destroy]
    resources :pricing_skus, except: :destroy do
      resources :prices, except: :show
    end
    resources :navigation_redirects, only: [:index, :show, :create, :edit, :destroy]
    resource :search, only: :show do
      member do
        get :live
      end
    end
    resource  :search_settings, only: [:show, :update]
    resources :search_customizations, except: :new do
      member do
        get :insights
        get :analyze
      end
    end

    resources :pricing_discounts, except: [:new, :create] do
      resources :redemptions, only: [:index], controller: 'pricing_discount_redemptions'

      member do
        get :rules
        get :insights
      end
    end
    resources :navigation_menus do
      collection do
        post :sort
        post :move
      end
    end
    resources :navigation_taxons do
      collection { get :select }

      member do
        get :select
        get :insert
        get :children
        patch :move
        patch :sort
      end
    end

    resource :direct_uploads, only: [:new, :create] do
      member do
        put 'upload/:type/:filename', action: :upload, as: :upload
        get :product_images
      end
    end

    resources :inventory_skus

    resources :users, except: :create do
      member do
        get :cart
        get :orders
        get :addresses
        get :permissions
        get :insights
        post :send_password_reset
        patch :unlock
      end
    end

    resources :unsubscribes, only: [] do
      member do
        get :status_report
        get :commentable
      end
    end

    resources :segments, except: [:new, :create] do
      resources :rules, except: [:show, :new, :edit], controller: 'segment_rules'
      resources :segmentables, only: [:index]

      member do
        get :insights
      end
    end
    resource :segment_override, only: [:show, :create]
    resources :segment_rules, only: [] do
      collection do
        get :geolocation_options
      end
    end

    resources :create_segments, except: :show do
      member do
        get :rules
        get :new_rule
        get 'edit_rule/:rule_id', action: :edit_rule, as: :edit_rule
        get :review
      end
    end

    resources :bookmarks, only: [:create, :destroy]

    resources :shipping_services
    resources :tax_categories do
      resources :tax_rates, except: :show, as: :rates, path: 'rates'

admin/app/views/workarea/admin/shared/_activate_select.html.haml
= inline_svg_tag 'workarea/admin/icons/calendar.svg', title: t('workarea.admin.shared.activate_select.when_does_this_activate'), class: 'release-select__icon'
= select_tag name, publishing_options_for_select, class: 'release-select__input', data: { unsaved_changes_ignore: '', publish_with_release_menu: 'async' }, id: nil
%span →

.tooltip-content{ data: { disable_publish_now_warning: '' } }
  %p= t('workarea.admin.shared.publishing_select.warning_message')

admin/app/views/workarea/admin/shared/_active_field.html.haml
.active-field
  = toggle_button_for "#{scope}[active]", model.active, data: { toggle_button: '' } do
    .toggle-button__more.toggle-button__more--to-right{ data: { toggle_button_positive_element: '' } }
      = link_to '#active-by-segment', data: { active_by_segment_tooltip: '' } do
        .active-field__segments-message
          - haml_tag_if model.segments.present?, :strong do
            = t('workarea.admin.shared.active_field.by_segment', name: model.segments.map(&:name).first, count: model.segments.size, more_count: model.segments.size - 1)
          - if model.segmented? && model.segments.blank?
            = link_to '#missing-segments-tooltip', data: { tooltip: '' } do
              = inline_svg_tag('workarea/admin/icons/alert.svg', class: 'svg-icon svg-icon--small svg-icon--red')
            #missing-segments-tooltip.tooltip-content
              %p= t('workarea.admin.shared.active_field.no_segments')

      #active-by-segment.tooltip-content
        %h3
          = inline_svg_tag('workarea/admin/icons/user.svg', class: 'svg-icon svg-icon--small svg-icon--blue')
          = t('workarea.admin.shared.active_field.active_by_segment')
        %p= t('workarea.admin.shared.active_field.description_html', segments_path: segments_path)

        .property
          = label_tag "#{scope}_active_segment_ids", t('workarea.admin.shared.active_field.only_for'), class: 'property__name'
          = select_tag "#{scope}[active_segment_ids]", options_from_collection_for_select(segments, :id, :name, model.active_segment_ids), multiple: true, data: { select: { placeholder: t('workarea.admin.shared.active_field.select_segments'), allowClear: true, dropdownParent: '#active-by-segment' } }

admin/app/views/workarea/admin/shared/_bulk_actions.html.haml
.grid.grid--auto.grid--middle
  - unless local_assigns.key?(:import) && !import
    .grid__cell= link_to t('workarea.admin.shared.bulk_actions.import'), new_data_file_import_path(model_type: klass, return_to: index_url_for(klass)), class: 'workflow-bar__button'

  - unless local_assigns.key?(:export) && !export
    .grid__cell
      = form_tag new_data_file_export_path, method: :get, data: { bulk_action_form: '' } do
        = hidden_field_tag 'model_type', klass
        - if local_assigns[:search].present?
          = hidden_field_tag 'query_id', search.to_gid_param
        = hidden_field_tag 'return_to', index_url_for(klass)
        %button.workflow-bar__button.workflow-bar__button--left-divide{ type: :submit }= t('workarea.admin.shared.bulk_actions.export')

  = yield
  = append_partials("admin.bulk_actions.#{klass.model_name.route_key}", local_assigns.slice(:klass, :search))

  - unless local_assigns.key?(:bulk_delete) && !bulk_delete
    = render('workarea/admin/bulk_action_deletions/form', model_type: klass, query_id: local_assigns[:search]&.to_gid_param)

  %div{ data: { bulk_action_count_placeholder: '' } }

admin/app/views/workarea/admin/shared/_creation_date.html.haml
.browsing-controls__filter.browsing-controls__filter--date
  %button.browsing-controls__filter-button{ type: 'button', data: { filter_dropdown: "#filters-dropdown-date" } }
    = t('workarea.admin.search.creation_date')
    = inline_svg_tag('workarea/admin/icons/calendar.svg', class: 'browsing-controls__filter-button-icon svg-icon svg-icon--small')

  #filters-dropdown-date.browsing-controls__filter-dropdown
    .grid
      .grid__cell.grid__cell--50
        .property.property--inline
          -# TODO v4 rename to created_at_starts_at, unify globally with partial
          = label_tag 'created_at_greater_than', t('workarea.admin.search.creation_date_filter'), class: 'property__name'
          = datetime_picker_tag 'created_at_greater_than', params[:created_at_greater_than], class: 'text-box', placeholder: t('workarea.admin.search.start_date'), data: { datepicker_field: { inline: true }, datepicker_field_starts_at: '' }
      .grid__cell.grid__cell--50
        .property.property--inline
          = datetime_picker_tag 'created_at_less_than', params[:created_at_less_than], class: 'text-box', placeholder: t('workarea.admin.search.end_date'), data: { datepicker_field: { inline: true }, datepicker_field_ends_at: '' }
    .browsing-controls__filter-dropdown-submit
      .grid.grid--auto.grid--middle.grid--center
        .grid__cell= label_tag 'quick_range', t('workarea.admin.date_selector.or_choose')
        .grid__cell= select_tag 'quick_range', options_for_select(date_selector_quick_range_options)
        .grid__cell= t('workarea.admin.date_selector.and')
        .grid__cell= submit_tag t('workarea.admin.search.submit'), name: 'filter_by_creation_date', class: 'button button--small'

admin/app/views/workarea/admin/shared/_csv_formatting_tooltip.html.haml
#csv-help.tooltip-content
  %p= t('workarea.admin.shared.csv_formatting_tooltip.tooltip_content_html')

  %p
    %strong= t('workarea.admin.shared.csv_formatting_tooltip.example')
    = t('workarea.admin.shared.csv_formatting_tooltip.escaping_commas_example')
    %br
    %strong= t('workarea.admin.shared.csv_formatting_tooltip.example')
    = t('workarea.admin.shared.csv_formatting_tooltip.escaping_double_quote_example')

admin/app/views/workarea/admin/shared/_date_selector.html.haml
-# TODO v4 consolidate all date filters UI to use this partial
.browsing-controls__filter.browsing-controls__filter--date
  %button.browsing-controls__filter-button{ type: 'button', data: { filter_dropdown: '#filters-dropdown-date' } }
    = t('workarea.admin.date_selector.date_range', starts_at: starts_at.to_s(:date_only), ends_at: ends_at.to_s(:date_only))
    = inline_svg_tag('workarea/admin/icons/calendar.svg', class: 'browsing-controls__filter-button-icon svg-icon svg-icon--small')

  #filters-dropdown-date.browsing-controls__filter-dropdown.tooltip-content
    .grid
      .grid__cell.grid__cell--50
        .property.property--inline
          = label_tag 'starts_at', t('workarea.admin.fields.starts_at'), class: 'property__name'
          = datetime_picker_tag 'starts_at', starts_at.to_s(:date_only), class: 'text-box', placeholder: t('workarea.admin.fields.starts_at'), data: { datepicker_field: { inline: true }, datepicker_field_starts_at: '' }
      .grid__cell.grid__cell--50
        .property.property--inline
          = datetime_picker_tag 'ends_at', ends_at.to_s(:date_only), class: 'text-box', placeholder: t('workarea.admin.fields.ends_at'), data: { datepicker_field: { inline: true }, datepicker_field_ends_at: '' }

    .browsing-controls__filter-dropdown-submit
      .grid.grid--auto.grid--middle.grid--center
        .grid__cell= label_tag 'quick_range', t('workarea.admin.date_selector.or_choose')
        .grid__cell= select_tag 'quick_range', options_for_select(date_selector_quick_range_options)
        .grid__cell= t('workarea.admin.date_selector.and')
        .grid__cell= submit_tag t('workarea.admin.search.submit'), class: 'button button--small'

admin/app/views/workarea/admin/shared/_message.html.haml
.message{ class: "message--#{type}" }
  %p.message__type
    %span.message__icon= type.titleize
  %p.message__text= message

admin/app/views/workarea/admin/shared/_primary_nav.html.haml
#primary_nav{ class: ('hidden' unless local_assigns[:visible].presence) }

  .primary-nav{ role: 'navigation' }

    .grid.grid--auto.grid--center
      .grid__cell= link_to "↑ #{t('workarea.admin.shared.primary_nav.main_dashboard')}", root_path, class: "primary-nav__home-link #{('primary-nav__home-link--hidden' if request.path == root_path)}"

    .search-form.search-form--major
      = form_tag search_path, method: 'get', role: 'search', target: '_parent' do
        = search_field_tag :q, nil, placeholder: t('workarea.admin.shared.primary_nav.search_placeholder'), title: t('workarea.admin.shared.primary_nav.search_placeholder'), tabindex: '0', class: 'search-form__input', data: { categorized_autocomplete_field: '' }, id: 'primary_nav_admin_search', aria: { label: t('workarea.admin.shared.primary_nav.search_placeholder') }
        = submit_tag t('workarea.admin.shared.primary_nav.search'), class: 'search-form__button'

    .primary-nav__menu
      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.site_planner'), releases_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          - if release_options.empty?
            %li{ class: "primary-nav__item" }
              %span= t('workarea.admin.shared.primary_nav.no_upcoming_releases')
            %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.create_one'), create_releases_path, class: navigation_link_classes(create_releases_path)

          - else
            - release_options.take(5).each do |release|
              %li{ class: "primary-nav__item" }
                = link_to url_for(release), class: navigation_link_classes(release_path(release)) do
                  = truncate(release.name, length: 20)
                  = surround '(', ')' do
                    - if release.publish_at.present?
                      = local_time(release.publish_at, :date_only)
                    - else
                      = t('workarea.admin.shared.primary_nav.not_scheduled')
            %li.primary-nav__item= link_to t('workarea.admin.shared.primary_nav.view_all_releases'), list_releases_path, class: navigation_link_classes(list_releases_path)

          = append_partials('admin.releases_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.store'), store_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.home_page'), current_system_page_content_for(:home_page), class: navigation_link_classes(url_for(current_system_page_content_for(:home_page)))
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.content_pages'), content_pages_path, class: navigation_link_classes(content_pages_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.assets'), content_assets_path, class: navigation_link_classes(content_assets_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.primary_navigation'), navigation_menus_path, class: navigation_link_classes(navigation_menus_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.taxonomy'), navigation_taxons_path, class: navigation_link_classes(navigation_taxons_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.system_pages'), content_index_path, class: navigation_link_classes(content_index_path)
          = append_partials('admin.store_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.catalog'), catalog_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.products'), catalog_products_path, class: navigation_link_classes(catalog_products_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.categories'), catalog_categories_path, class: navigation_link_classes(catalog_categories_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.pricing'), pricing_skus_path, class: navigation_link_classes(pricing_skus_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.inventory'), inventory_skus_path, class: navigation_link_classes(inventory_skus_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.fulfillment'), fulfillment_skus_path, class: navigation_link_classes(fulfillment_skus_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.shipping'), shipping_skus_path, class: navigation_link_classes(shipping_skus_path)
          = append_partials('admin.catalog_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.orders'), orders_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.all_orders'), orders_path, class: navigation_link_classes(orders_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.todays_orders'), todays_orders_path, class: navigation_link_classes(todays_orders_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.yesterdays_orders'), yesterdays_orders_path, class: navigation_link_classes(yesterdays_orders_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.payment_transactions'), payment_transactions_path, class: navigation_link_classes(payment_transactions_path)
          = append_partials('admin.orders_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.people'), people_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.all_people'), users_path, class: navigation_link_classes(users_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.customers'), customers_path, class: navigation_link_classes(customers_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.administrators'), administrators_path, class: navigation_link_classes(administrators_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.segments'), segments_path, class: navigation_link_classes(segments_path)
          = append_partials('admin.people_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.search'), search_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          - current_popular_searches.each do |result|
            %li{ class: "primary-nav__item" }= link_to result['query_string'], search_customizations_path(q: result['query_string']), data: { method: 'post' }, class: navigation_link_classes(search_customization_path(result['query_string']))
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.customizations'), search_customizations_path, class: navigation_link_classes(search_customizations_path)
          = append_partials('admin.search_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.marketing'), marketing_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.discounts'), pricing_discounts_path, class: navigation_link_classes(pricing_discounts_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.transactional_emails'), content_emails_path, class: navigation_link_classes(content_emails_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.promo_codes'), pricing_discount_code_lists_path, class: navigation_link_classes(pricing_discount_code_lists_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.email_signups'), email_signups_path, class: navigation_link_classes(email_signups_path)
          = append_partials('admin.marketing_menu')

      = append_partials('admin.primary_nav')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.reports'), reports_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.timeline'), timeline_report_path, class: navigation_link_classes(timeline_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.insights'), insights_report_path, class: navigation_link_classes(insights_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.sales_over_time'), sales_over_time_report_path, class: navigation_link_classes(sales_over_time_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.average_order_value'), average_order_value_report_path, class: navigation_link_classes(average_order_value_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.sales_by_product'), sales_by_product_report_path, class: navigation_link_classes(sales_by_product_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.customers'), customers_report_path, class: navigation_link_classes(customers_report_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.searches'), searches_report_path, class: navigation_link_classes(searches_report_path)
          = append_partials('admin.reports_menu')

      .primary-nav__section
        .primary-nav__heading= link_to t('workarea.admin.shared.primary_nav.settings'), settings_dashboards_path, tabindex: 0, class: 'primary-nav__heading-link'
        %ul.primary-nav__children
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.configuration'), configuration_path, class: navigation_link_classes(configuration_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.search'), search_settings_path, class: navigation_link_classes(search_settings_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.tax_categories'), tax_categories_path, class: navigation_link_classes(tax_categories_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.shipping_services'), shipping_services_path, class: navigation_link_classes(shipping_services_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.redirects'), navigation_redirects_path, class: navigation_link_classes(navigation_redirects_path)
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.data_files'), data_files_path, class: navigation_link_classes(data_files_path)
          = append_partials('admin.settings_menu')
          %li{ class: "primary-nav__item" }= link_to t('workarea.admin.shared.primary_nav.trash'), trash_index_path, class: navigation_link_classes(trash_index_path)

admin/app/views/workarea/admin/shared/_publishing_select.html.haml
= inline_svg_tag 'workarea/admin/icons/calendar.svg', title: t('workarea.admin.shared.publishing_select.when_do_these_changes_publish'), class: 'release-select__icon'
= select_tag :publishing, publishing_options_for_select, class: 'release-select__input', data: { unsaved_changes_ignore: '', publish_with_release_menu: 'async' }, id: nil
%span →

.tooltip-content{ data: { disable_publish_now_warning: '' } }
  %p= t('workarea.admin.shared.publishing_select.warning_message')